ALTER TABLE "QboTaxCode"
  ADD COLUMN IF NOT EXISTS "salesTaxRateList" JSONB NOT NULL DEFAULT '[]'::JSONB,
  ADD COLUMN IF NOT EXISTS "combinedSalesRate" DECIMAL(9,6);

ALTER TABLE "QboTaxRate"
  ALTER COLUMN "rateValue" DROP NOT NULL;
